name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every day
    - cron: "0 1 * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    environment: TODOIST
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: '${{ secrets.TODOIST_API_KEY }}'
          PREMIUM: ""
